[general]
working_directory = "$HOME"
import =  [
    # "./catppuccin-latte.toml",
    "./catppuccin-mocha.toml",
    "./alacritty-local.toml"
]

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

builtin_box_drawing = true

[font.glyph_offset]
x = 0
y = 1

[font.offset]
x = 0
y = 4

[terminal.shell]
program = "/bin/zsh"  # Path to your preferred shell
args = ["-l"]

[window]
opacity = 0.85
blur = true
padding = { x = 2, y = 2 }
dynamic_padding = true
decorations = "full"
